# Site settings
title:       Fionn Concannon
email:       fionn@oceanlabs.co
author:      Fionn Concannon
description: "Fionn Concannon"
baseurl:     ""
url:         "http://www.fionnconcannon.com"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username:
twitter_username:
google_plus_id:
linkedin_username:fionn.concannon@gmail.com
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
